version: '3.0'
services:
  rabbitmq:
    restart: always
    image: rabbitmq:3.9.11-management
    container_name: rabbitmq
    hostname: localhost
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
#    volumes:
#      - ./data:/var/lib/rabbitmq
#      - ./conf:/etc/rabbitmq