spring:
  application:
    name: demo2
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  rabbitmq:
    addresses: localhost:5672
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
server:
  port: 8769
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
