spring:
  application:
    name: demo1
  rabbitmq:
    addresses: localhost:5672
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: Beijing
      config:
        server-addr: localhost:8848
        # 是否临时实例
        # ephemeral: false
        # namespace: xxxxxx-xxxxx-xxxx


server:
  port: 8762

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

demo2:
  ribbon:
    # 负载均衡策略：默认轮询可以改为集群优先、随机
    # 随机
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    # 集群优先
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

ribbon:
  eager-load:
    enabled: true
    clients:
    - demo2
    - javademo

#feign:
#  client:
#    config:
#      default:
#        loggerLevel: FULL


logging:
  level:
    com:
      example:
        demo1:
          controller: debug
    micro:
      service:
        demo:
          clients: debug

feign:
  httpclient:
    enabled: true
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 每个路径最大连接数